// This model establishes and exports our Rating schema for our Mongo Database. By doing this, we can easily create and delete any rating obect,
// as well as allowing us to easily identify and link the rating to a specific Writing and Author.
// Module created in part by Dylan Britain, Trey Boyer, and Minjing Liang

// Require Mongoose in order to interface with our MongoDB
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// Establish Rating Schema for MongoDB
// Note that the id field is automatically generated by MongoDB and does not need to be specified in the Schema
// Additionally, rather than specifying an authorId field, the has-one relationship can automatically be handled by specifying the 'author' parameter in the Schema as a User Schema
const ratingSchema = new Schema({
    body: String,
    ratingValue: Number,
    author: {
        type: Schema.Types.ObjectId,
        ref: "User",
    },
});

// Export ratingSchema
module.exports = mongoose.model("Rating", ratingSchema);
